services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodbdata:/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
